n = input('digite algo: ')
print(n.isnumeric(),'isnumeric')
print(n.isalpha(),'alpha')
print(n.isalnum(),'alnum')
print(n.isupper(),'upper')
print(n.islower(),'lower')
print(n.isspace(),'space')
print(n.istitle(),'title')
print(n.isdigit(),'digit')
print(n.isidentifier(),'identifier')
print(n.isprintable(),'printable')
print(n.isdecimal(),'decimal')
print(n.isascii(),'ascii')