nome = str(input('Digite seu nome:')).strip()
separa = nome.split()
print(separa)
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
print('seu ultimo nome contém ao todo {} letras'.format(len(nome.split()[-1])))
print('Seu primeiro nome é {} e contém ao todo {} letras'.format(nome.split()[0], len(nome.split()[0])))
print('Seu sobrenome é {} e contém ao todo {} letras'.format(nome.split()[-1], len(nome.split()[-1])))