número = input('Digite um número de 0 a 9999: ')
u = número.count('3')
d = número.count('2')
c = número.count('1')
m = número.count('0')
print ('Unidade: {}'.format(u))
print ('Dezena: {}'.format(d))
print ('Centena: {}'.format(c))
print ('Milhar: {}'.format(m))